backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
site_url: "https://www.skyray.io"

collections:
  - name: 'game'
    label: 'game'
    identifier_field: "en_title"
    format: 'json'
    folder: 'assets/content/game'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'EN Title', name: 'en_title', widget: 'string' }
      - { label: 'KR Title', name: 'kr_title', widget: 'string' }
      - { label: 'EN Author', name: 'en_author', widget: 'string' }
      - { label: 'KR Author', name: 'kr_author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'EN Description', name: 'en_description', widget: 'string' }
      - { label: 'KR Description', name: 'kr_description', widget: 'string' }
      - { label: 'EN Body', name: 'en_body', widget: 'markdown' }
      - { label: 'KR Body', name: 'kr_body', widget: 'markdown' }
      - { label: "Category", name: "category", widget: "hidden", default: "game" }
      - {label: "Translation", name: "translation", widget: "boolean", default: false}
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        default: "/img/game-1926905_640.png"
        media_library:
          config:
            multiple: true
      - label: "Original Author Image"
        name: "original_author"
        widget: "image"
        default: "/img/author_default.jpg"
        media_library:
          config:
            multiple: false
  - name: 'tech'
    label: 'tech'
    identifier_field: "en_title"
    format: 'json'
    folder: 'assets/content/tech'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'EN Title', name: 'en_title', widget: 'string' }
      - { label: 'KR Title', name: 'kr_title', widget: 'string' }
      - { label: 'EN Author', name: 'en_author', widget: 'string' }
      - { label: 'KR Author', name: 'kr_author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'EN Description', name: 'en_description', widget: 'string' }
      - { label: 'KR Description', name: 'kr_description', widget: 'string' }
      - { label: 'EN Body', name: 'en_body', widget: 'markdown' }
      - { label: 'KR Body', name: 'kr_body', widget: 'markdown' }
      - { label: "Category", name: "category", widget: "hidden", default: "tech" }
      - {label: "Translation", name: "translation", widget: "boolean", default: false}
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        default: "/img/code-1970468_640.png"
        media_library:
          config:
            multiple: true
      - label: "Original Author Image"
        name: "original_author"
        widget: "image"
        default: "/img/author_default.jpg"
        media_library:
          config:
            multiple: false